const verses = [
  {
    verse: { text: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
    prayer: "Heavenly Father, my Shepherd and Guide, I come before You with a heart full of gratitude for Your unfailing care. In a world that constantly tells me I need more, help me to rest in the profound truth that because You are my Shepherd, I lack nothing of eternal value. You see my needs before I even speak them, and You provide for me in ways I cannot always see. Quiet the anxious whispers of my heart that chase after worldly security, and teach me to find my complete sufficiency in You alone. Lead me beside the still waters of Your peace, restore my soul when it is weary from the battles of life, and guide me along the right paths for Your name's sake. Even when I walk through the darkest valleys of uncertainty, grief, or fear, may I fear no evil, for I know You are with me. Your rod of correction and Your staff of guidance, they comfort me, assuring me that I am never alone and that Your love pursues me all the days of my life. May this deep, abiding trust in Your shepherding heart be the foundation upon which I build this day and every day. Amen."
  },
  {
    verse: { text: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    prayer: "Lord Jesus, my Source of unfailing strength, I humbly acknowledge that on my own, my power is limited, my wisdom is flawed, and my courage often fails. Yet, in You, I find a strength that is made perfect in my weakness. As I face the tasks and challenges of this day—both the expected and the unforeseen—I declare my dependence on You. I do not need to face them in my own ability, for Your Spirit lives within me. Empower me to speak words of kindness when I am tempted to be harsh. Grant me perseverance to complete the work set before me when I feel like giving up. Give me wisdom to make decisions that honor You when the path is unclear. Help me to love others with the same unconditional love You have shown me. May I not boast in my own capabilities, but in the limitless strength You supply. Let this truth sink deep into my spirit, banishing all thoughts of inadequacy and replacing them with a confident trust that through You, I can overcome any obstacle, endure any trial, and fulfill the purpose You have for my life. In Your mighty name, I pray. Amen."
  },
  {
    verse: { text: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5-6" },
    prayer: "Almighty God, the Author of all wisdom, I confess that my own understanding is limited and often leads me astray. I see only a tiny fragment of the picture, while You see the beginning from the end. Today, I make a conscious choice to trust You with my whole heart—not just with the parts that are easy to surrender, but with my deepest fears, my unanswered questions, and my most cherished dreams. It is so tempting to rely on my logic, my feelings, or the advice of the world to navigate my life. But I choose instead to lean on You. When I don't understand my circumstances, help me to trust Your character. When I can't see the way forward, help me to trust Your guidance. I ask for the grace to acknowledge You in all my ways—in my work, my relationships, my thoughts, and my plans. And I hold onto Your precious promise: that when I do, You will make my paths straight. Not necessarily easy, but straight—directed towards Your purpose and filled with Your presence. In Jesus' name, Amen."
  },
  {
    verse: { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", reference: "Joshua 1:9" },
    prayer: "Lord God, my Commander and Shield, the command to be strong and courageous can feel overwhelming in the face of life's giants. Fear and discouragement often knock at the door of my heart, whispering lies of inadequacy and defeat. But today, I stand on Your powerful command, which is not based on my own strength, but on the unshakable promise of Your presence. You, the Creator of the universe, the King of kings, declare that You will be with me wherever I go. What then can man do to me? What circumstance can ultimately harm my soul? Fill me with a holy courage that is not the absence of fear, but the determination to move forward despite it, because I know You go before me. When I am tempted to retreat, push me forward. When I feel alone, wrap me in the comfort of Your Spirit. Help me to be an agent of Your courage to those around me who are also struggling. I will not be afraid, I will not be discouraged, for You, O Lord, are with me. Amen."
  },
  {
    verse: { text: "Give thanks to the Lord, for He is good; His love endures forever.", reference: "Psalm 107:1" },
    prayer: "Gracious and Eternal Father, my heart overflows with praise as I meditate on Your enduring goodness. In a world that is constantly changing, where people fail, circumstances shift, and feelings fluctuate, You remain the same—perfectly good, infinitely loving, and eternally faithful. I thank You not just for the tangible blessings I can see, but for the gift of Your very self. Thank You for the breath in my lungs, for the beauty of creation, for the love of family and friends. Most of all, I thank You for Your love that endures forever—a love that pursued me before I knew You, that redeemed me when I was lost, and that sustains me even now. Help me to cultivate a lifestyle of gratitude. May my first thought in the morning be of thanks, and my last thought at night be of praise. Let this spirit of thankfulness transform my perspective, turning my focus from what I lack to the abundance of Your grace. I praise You, for You are good, and Your love has no end. Amen."
  },
  {
    verse: { text: "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?", reference: "Psalm 27:1" },
    prayer: "Lord Jesus, You are the Light that shatters my darkness and the Salvation that rescues my soul. When fear tries to cast its long, intimidating shadow over my life, I will remember who You are. You are my Light, guiding me through the fog of confusion and illuminating the path of truth. Because of You, I no longer have to stumble in the darkness of despair or sin. You are my Salvation, the One who has delivered me from the ultimate power of death and hell. What temporary fear can compare to such a great salvation? You are the Stronghold of my life, the unbreachable fortress where my soul is safe. When the enemy attacks with lies, when anxiety storms my mind, I can run to You and find perfect security. So I declare today: I will not be afraid of people, of the future, of failure, or of death. My life is hidden with Christ in God. In You, I am safe. In You, I am secure. Fill me with the boldness that comes from knowing the Mighty One is on my side. Amen."
  },
  {
    verse: { text: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
    prayer: "Compassionate Father, You know the weight I carry. You see the worries that tumble through my mind in the quiet hours of the night—concerns for my family, my health, my future, my purpose. You invite me, not to simply 'let go' in my own strength, but to actively cast all of my anxiety upon You. This is an act of trust, a deliberate decision to transfer the burden from my weak shoulders to Your strong ones. Today, I take You up on this invitation. I lay down at Your feet the heavy load of worry about [mention specific concerns if desired]. I release the need to control outcomes, to know the future, to fix every problem. I thank You that this command is based on a profound truth: that You deeply, personally, and perfectly care for me. You are not a distant, uninterested deity. You are my loving Father who is attentive to every tear and every sigh. As I release my anxieties to You, I ask You to fill the emptied spaces with Your perfect peace—a peace that surpasses all understanding and will guard my heart and mind in Christ Jesus. Amen."
  },
  {
    verse: { text: "Your word is a lamp to my feet and a light to my path.", reference: "Psalm 119:105" },
    prayer: "Lord God, I praise You for the precious gift of Your Word. In a world filled with conflicting voices, shifting morals, and confusing philosophies, Your Word stands as a firm and reliable guide. It is not a blinding spotlight that shows me the entire journey from start to finish all at once, which might overwhelm me. Instead, it is a faithful lamp to my feet, providing just enough light for the very next step I need to take. And it is a light to my path, illuminating the general direction You have for my life. I confess that I do not always prioritize reading, studying, and meditating on Your Word. Forgive me for trying to navigate the darkness of this world by my own faulty wisdom. Today, renew in me a hunger for Your truth. Open my eyes to see wonderful things in Your law. May its precepts guide my decisions, its promises anchor my soul, and its commands shape my character. Let it be the final authority in my life, the standard by which I measure all other voices. May I not just be a hearer of the Word, but a doer, walking confidently in the light You provide. Amen."
  },
  {
    verse: { text: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
    prayer: "Mighty Warrior God, I come to You today feeling the pressure of battles that are too big for me. Like the Israelites trapped between the Red Sea and the Egyptian army, I sometimes feel surrounded by problems with no way out. In those moments, my natural instinct is to panic, to strive, and to try to fix everything in my own frantic power. But Your Word speaks a different word over me today: 'Be still.' This is not a call to passive resignation, but to active, trust-filled surrender. It is a command to cease from my anxious striving, to take my hands off the situation, and to watch You work. Thank You that the battle is not mine, but Yours. You are the Lord of Hosts, the One who parts seas, topples walls, and defeats every enemy of my soul. Help me to be still before You—to quiet my heart in prayer, to wait expectantly for Your intervention, and to trust in Your perfect timing. I declare my confidence that You will fight for me today. I will be still and know that You are God. Amen."
  },
  {
    verse: { text: "Rejoice in the Lord always. I will say it again: Rejoice!", reference: "Philippians 4:4" },
    prayer: "Lord of Joy, this command from Your apostle Paul is both beautiful and challenging. Rejoice always? Even when circumstances are difficult? Even when my heart is heavy? Even when the world seems dark? You are not asking me to put on a fake smile or to deny the reality of my pain. You are calling me to a deeper, more resilient joy—a joy that is rooted not in my changing circumstances, but in Your unchanging character. I choose to rejoice in You, Lord! I rejoice because You are good. I rejoice because I am forgiven. I rejoice because You are with me. I rejoice because my future is secure in Your hands. This joy is my strength. Help me to cultivate it daily through gratitude, through worship, and through focusing on Your faithfulness. When the enemy tries to steal my joy with bad news or difficult people, remind me of the eternal reasons I have to rejoice. May the joy of the Lord be my stronghold today, and may it spill over onto everyone I meet. I will say it again: I will rejoice in You! Amen."
  },
  {
    verse: { text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", reference: "Romans 8:28" },
    prayer: "Sovereign God, in a world filled with pain, confusion, and events that seem random or unfair, this promise is an anchor for my soul. I don't always understand my circumstances. I don't see how heartbreak, loss, or disappointment could possibly lead to any good. But I choose to trust the One who is weaving the tapestry. You are the Master Weaver, and I only see the tangled, chaotic threads on the underside. You see the beautiful, complete picture that is being formed. I thank You that this promise applies to 'all things'—not just the good things, but the hard things, the confusing things, the things that seem like mistakes. You are able to take every single piece of my life, even the broken ones, and work them together for my ultimate good and Your glory. This 'good' is not my definition of comfort or ease, but Your definition of conformity to the image of Your Son. Help me to trust Your process, even when I don't understand Your plan. Give me patience to wait for the good You are bringing forth, and faith to believe that You are always, always working. Amen."
  },
  {
    verse: { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", reference: "Isaiah 40:31" },
    prayer: "Lord, the Source of all strength and power, I come to You weary and worn. The race of life is long, and I often find myself running on empty. My own energy is depleted, my motivation is low, and I feel the weight of fatigue in my body, mind, and spirit. But You are the God who does not grow tired or weary, and You promise to renew the strength of those who put their hope in You. Today, I fix my hope on You—not on my own abilities, not on a change in circumstances, but on Your faithful, unchanging character. I ask You to renew my strength. Lift me up on wings like an eagle, giving me a fresh, heavenly perspective above my problems. Grant me the stamina to run the race You have set before me without growing weary. And teach me the grace of walking daily with You, step-by-step, without fainting. I cannot do this in my own power. I need Your supernatural strength to fill me, sustain me, and carry me forward. I place my hope in You alone. Amen."
  },
  {
    verse: { text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", reference: "2 Corinthians 5:17" },
    prayer: "Heavenly Father, what an incredible, life-transforming truth! In Christ, I am not just improved, repaired, or patched up. I am a new creation. The old life, with its guilt, its shame, its failures, and its patterns of sin, has passed away. It is gone, buried with Christ in His death. And in its place, something brand new has come! I have been raised with Christ to walk in newness of life. Sometimes, Father, I still feel the pull of the old person I used to be. The old habits, the old thought patterns, the old temptations try to resurface. Help me to live today in the reality of who I now am in Christ. I am not defined by my past; I am defined by Your grace. I am not a sinner trying to be good; I am a saint, a holy child of God, learning to live out my true identity. Renew my mind with this truth. Help me to see myself and others through the lens of the new creation. Let the freshness of Your life flow through me, producing fruit that lasts. Thank You for making me new. Amen."
  },
  {
    verse: { text: "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.", reference: "Ephesians 4:32" },
    prayer: "Merciful Father, I am in awe of the forgiveness You have shown me in Christ. You didn't wait for me to get my act together or to deserve it. While I was still a sinner, still rebellious, still hurting You with my choices, You sent Your Son to die for me, cancelling my debt completely and forever. This profound, undeserved forgiveness is now to be the model for my relationships with others. Lord, I confess that sometimes forgiveness is hard. Holding onto a grudge can feel like a form of control, and letting go of an offense can feel like letting the other person off the hook. But Your Word calls me to a different way—a way of kindness, tenderheartedness, and radical forgiveness. Help me to extend to others the same grace You have extended to me. When I am hurt, help me to remember how much I have been forgiven. Replace my bitterness with Your compassion, my resentment with Your love. Make me an instrument of Your peace and reconciliation in every relationship I have today. Amen."
  },
  {
    verse: { text: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", reference: "2 Timothy 1:7" },
    prayer: "Lord God, I reject the lie that fear is just a normal part of life that I have to accept. Your Word clearly states that the spirit of fear—the kind that paralyzes, torments, and controls—does not come from You. It comes from the enemy. But You, my Father, have equipped me with a different spirit. You have given me power—Your own supernatural strength to overcome obstacles and stand firm. You have given me love—a perfect love that casts out all fear, a love that focuses on You and on others rather than on my own anxieties. And You have given me a sound mind—a mind that is disciplined, clear, and able to think Your thoughts after You, rather than being tossed about by every fearful imagination. Today, I choose to walk in the spirit You have given me. When fear tries to grip my heart, I will declare Your truth. I am powerful in Christ. I am loved with an everlasting love. I have the mind of Christ. Help me to live in this freedom today. Amen."
  },
  {
    verse: { text: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28" },
    prayer: "Gentle and Lowly Jesus, I hear Your tender invitation, and I accept it. I come to You just as I am—weary from the struggles, burdened by responsibilities, and tired of carrying weights I was never meant to bear. The world offers distractions to make me forget my burdens, but You offer true rest for my soul. You don't scold me for being tired. You don't give me a list of things I must do first. You simply say, 'Come.' So I come, laying down at Your feet the heavy yoke of people-pleasing, the crushing weight of worry, the exhausting effort of trying to earn love and approval. I exchange my heavy yoke for Yours, for Your yoke is easy and Your burden is light. Teach me to walk in step with You, to learn from Your gentle and humble heart. Give me rest—not just physical rest, but deep, soul-level rest. Rest from striving, rest from guilt, rest from fear. I praise You for being the place where my weary soul can always find a home. Amen."
  },
  {
    verse: { text: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.", reference: "Galatians 2:20" },
    prayer: "Lord Jesus, this is the great mystery and miracle of the Christian life—that my old self, with its self-centered ambitions and futile attempts at righteousness, has been crucified with You. That person died. And in its place, something amazing has happened: You now live in me! My life is not about trying harder to be good; it is about allowing You, the risen Christ, to live Your life through me. This is so liberating, and yet so challenging to live out practically. Today, I yield every part of my being to You—my thoughts, my words, my actions, my desires. I choose to live by faith, trusting not in my own ability, but in Your life flowing through me. I am loved by You, the Son of God, who gave Yourself for me personally. That love is the fuel for my life. Help me to decrease today, so that You may increase. May others not see me, but see something of Your beauty, Your grace, and Your truth shining through. Live in me and through me, I pray. Amen."
  },
  {
    verse: { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", reference: "Philippians 4:6-7" },
    prayer: "Faithful Father, You know the countless thoughts that race through my mind—the 'what ifs,' the worries about tomorrow, the concerns for those I love. Your Word gives me a clear and powerful prescription for anxiety: don't worry, but pray. This is not a suggestion, but a loving command for my own well-being. Today, I choose to bring every single anxious thought to You in prayer. I present my requests to You clearly and specifically, laying them at Your throne. And I do this with thanksgiving, choosing to focus on Your past faithfulness as I trust You for the future. I ask You now to do what only You can do: let Your peace—a peace so profound it doesn't make sense to the world, a peace that transcends all understanding—guard my heart and my mind. Like a soldier standing watch, let Your peace protect me from the attacks of worry and fear. May it keep me safe and secure in Christ Jesus, my Prince of Peace. Amen."
  },
  {
    verse: { text: "Jesus Christ is the same yesterday and today and forever.", reference: "Hebrews 13:8" },
    prayer: "Eternal, Unchanging God, in a world where everything is in constant flux—where relationships change, health fails, economies shift, and cultures transform—I cling to the rock-solid truth of Your unchanging nature. You are the same yesterday, today, and forever. The God who parted the Red Sea, who walked with Daniel in the lion's den, who comforted the weeping Mary at the tomb—that same God is with me right now. Your character never wavers; Your love never cools; Your power never diminishes; Your promises never fail. When my own feelings fluctuate and my circumstances are unstable, I anchor my soul in You. I can trust You today because You have been faithful to countless generations before me. I can hope for tomorrow because Your faithfulness will extend into eternity. Thank You for being my sure foundation, my constant hope, my unchanging Friend. Help me to rest in the security of who You are. Amen."
  },
  {
    verse: { text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", reference: "Matthew 6:33" },
    prayer: "Lord and King, I confess that my priorities often get tangled. I spend so much energy worrying about the 'things' of life—what I will eat, what I will wear, where I will live, how my future will unfold. The world screams at me to pursue security, comfort, and success. But You call me to a different pursuit. You call me to seek first Your kingdom and Your righteousness. Help me to realign my heart today. May my primary ambition be to see Your rule and reign established in my own heart and in the world around me. May my deepest desire be to live in right relationship with You and to reflect Your character in all I do. I choose to trust that when I make Your kingdom my priority, You will take care of all the other things—my needs, my concerns, my future. You are a good Father who knows what I need before I ask. Give me faith to put You first, and the peace that comes from knowing You will provide for the rest. Amen."
  },
  {
    verse: { text: "Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil’s schemes.", reference: "Ephesians 6:10-11" },
    prayer: "Mighty Commander of the Heavenly Armies, I am keenly aware that my struggle is not merely against flesh and blood—against difficult people or challenging circumstances—but against spiritual forces of evil. I cannot fight this battle in my own strength, for I am no match for the enemy's schemes. Therefore, I put my trust in Your mighty power. I ask You to help me put on the full armor that You have so graciously provided. Gird my waist with Your belt of truth, so I can discern lies from reality. Place upon my chest the breastplate of righteousness, the righteousness of Christ that protects my heart. Fit my feet with the readiness that comes from the gospel of peace, so I can stand firm and move forward for You. Take up the shield of faith, with which I can extinguish all the flaming arrows of the evil one. Place on my head the helmet of salvation, the assurance of my security in You. And place in my hand the sword of the Spirit, Your living and active Word. Help me to stand firm today, dressed in Your power, not mine. Amen."
  },
  {
    verse: { text: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
    prayer: "Lord God Almighty, Your name is more than a title; it represents Your very character—Your power, Your love, Your faithfulness, Your holiness. And that name is a fortified tower, an unassailable place of safety and refuge. Today, I run to You. When the enemy accuses me, I run to the name of Jesus, my Righteousness, and I am safe. When the storms of life rage around me, I run to the name of Jehovah Shalom, the Lord is Peace, and I am safe. When I feel weak and vulnerable, I run to the name of Jehovah Nissi, the Lord is my Banner, and I am safe. When I am confused and need guidance, I run to the name of Jehovah Rohi, the Lord is my Shepherd, and I am safe. You are my refuge and my fortress, my God, in whom I trust. I declare that no weapon formed against me shall prosper, for I am hidden in the strong tower of Your name. Thank You for this perfect security. Amen."
  },
  {
    verse: { text: "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.", reference: "1 Corinthians 15:58" },
    prayer: "Faithful God, in a world that is constantly shifting, give me the grace to stand firm. Let nothing move me from the foundation of my faith in Christ. When circumstances tempt me to doubt, help me to stand on Your promises. When the world pressures me to conform, help me to stand on Your truth. When my flesh grows weary, help me to stand in Your strength. And not only to stand, but to give myself fully to the work You have called me to do. Whether it is serving my family, working with integrity, loving my neighbor, or sharing my faith, remind me that my labor in You is never in vain. It has eternal significance. The small acts of kindness, the difficult words of forgiveness, the hidden sacrifices—You see them all, and they matter. They are building blocks for Your eternal kingdom. So today, I commit to standing firm and working diligently, not for my own glory, but for Yours, knowing that my reward is sure. Amen."
  },
  {
    verse: { text: "Create in me a clean heart, O God, and renew a right spirit within me.", reference: "Psalm 51:10" },
    prayer: "Merciful and Holy God, like David, I come before You aware of my own sinfulness and my desperate need for Your cleansing grace. The world's pollution, my own selfish desires, and the temptations I face daily can leave my heart stained and my spirit weary. I cannot clean myself. I cannot renew my own spirit. Only You can do that. So I humbly ask: Create in me a clean heart, O God. Not just a slightly improved heart, but a clean one—washed by the blood of Jesus, purified by Your Spirit. Remove the guilt that weighs me down, the shame that holds me back, and the impurity that dims my vision of You. And renew a right spirit within me. Restore in me the joy of my salvation, and grant me a willing spirit to sustain me. Give me a steadfast spirit that won't be blown off course. Give me a humble spirit that depends on You. Give me a loving spirit that reflects Your heart to others. Create in me, Lord, the person You designed me to be. Amen."
  },
  {
    verse: { text: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.", reference: "Zephaniah 3:17" },
    prayer: "Abba Father, this verse paints a picture of Your love that is almost too wonderful to comprehend. You are the Mighty Warrior who saves, fighting on my behalf with power and might. But You are also the tender Father who takes great delight in me. You don't just tolerate me; You delight in me! You rejoice over me with singing. When I feel insignificant, remind me that the God of the universe finds joy in me. When I feel like a failure, remind me that Your love is not based on my performance. When I feel condemned, remind me that in Christ, the rebuke is gone, replaced by Your rejoicing. Let this truth sink deep into the core of my being. I am loved with an everlasting love. I am the object of Your delight. Help me to live today in the freedom and joy of being Your beloved child, secure in Your love, and confident in Your saving power. I love You, Lord. Amen."
  },
  {
    verse: { text: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", reference: "Philippians 4:19" },
    prayer: "Jehovah Jireh, My Provider, I lift my eyes to You, the source of every good and perfect gift. You know every need I have—physical, emotional, spiritual, and relational. You see the financial pressures, the health concerns, the deep longings of my heart, and the areas where I feel empty and lacking. Your Word promises that You will meet all my needs, not according to my limited resources or my deserving, but according to the boundless riches of Your glory in Christ Jesus. You own the cattle on a thousand hills. The earth is Yours and everything in it. You are not limited by my circumstances. Today, I bring my needs before You, trusting in Your abundant provision. Help me to distinguish between my genuine needs and my mere wants. Give me contentment in whatever circumstances You provide. And open my eyes to see the many ways You are already providing for me, often through unexpected channels. I trust You, Lord, to supply everything I truly need, in Your perfect way and timing. Amen."
  },
  {
    verse: { text: "Draw near to God, and he will draw near to you.", reference: "James 4:8" },
    prayer: "Lord God, what a simple yet profound promise! You are not a distant, uninterested deity. You are a loving Father who longs for intimate relationship with Your children. You promise that the initiative I take to draw near to You will be met by Your even greater initiative to draw near to me. Today, I choose to take that step. I quiet the noise of the world and the distractions in my own mind to focus my heart on You. I draw near to You through prayer, pouring out my heart and listening for Your still, small voice. I draw near to You through Your Word, seeking to know Your heart and Your ways. I draw near to You through worship, lifting my eyes from my problems to gaze upon Your beauty and majesty. And as I do, I trust that You are drawing near to me. Fill the space between us with Your presence. Let me sense Your nearness, not just as a feeling, but as a settled conviction in my soul. I long for You, Lord. I draw near. Amen."
  },
  {
    verse: { text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", reference: "John 3:16" },
    prayer: "Heavenly Father, this single verse is the gospel in a nutshell, the greatest truth the universe has ever known. It tells me that the motivation behind all of history, behind creation, behind Your every action, is love. You so loved—not just a little, but with an infinite, boundless, sacrificial love. And this love wasn't just a feeling; it was an action. You gave. You gave what was most precious to You, Your one and only Son, Jesus. You gave Him to live for me, to die for me, and to rise again. Why? So that whoever—anyone, everyone, including me—who simply believes in Him, will not perish, will not be lost forever in the darkness of sin and death, but will have eternal life. Not just life that goes on forever, but a new quality of life, abundant and full, beginning now and lasting for eternity. Thank You seems so inadequate for such a gift. I receive Your love today. I believe in Your Son. And I stand in awe of the price You paid to call me Your own. Amen."
  },
  {
    verse: { text: "Let the peace of Christ rule in your hearts... and be thankful.", reference: "Colossians 3:15" },
    prayer: "Prince of Peace, I invite You to rule in my heart today. The word 'rule' here means to act as an umpire, to make the final call. So often, I let other things rule my heart—anxiety, anger, resentment, circumstances, the opinions of others. Today, I ask that Your peace would be the deciding factor. When I am tempted to react in anger, let Your peace step in and make the call for calm. When I am tempted to worry, let Your peace step in and declare that You are in control. When I am torn between two decisions, let Your peace guide me towards the one that aligns with Your will. And alongside this peace, cultivate in me a deep and abiding thankfulness. Let gratitude be the soil in which Your peace grows. I thank You for Your presence, Your provision, and Your purpose for my life. May Your peace, which transcends all understanding, rule in my heart today and every day. Amen."
  },
  {
    verse: { text: "We love because he first loved us.", reference: "1 John 4:19" },
    prayer: "God of Love, this simple sentence holds the key to all true love. My capacity to love—whether it's my family, my friends, my neighbors, or even my enemies—does not originate within myself. My heart is too often selfish, fearful, and conditional in its love. But You are the source. You are love itself. And the reason I can love at all is because You first loved me. You loved me when I was unlovable. You pursued me when I was running away. Your love initiated, and my love is merely a response. Today, I want to be a channel of Your love to the world around me. Fill me so full of Your love that it naturally overflows to others. Help me to love the difficult person with Your patience. Help me to love the lonely person with Your compassion. Help me to love my enemy with Your grace. I cannot manufacture this love, but I can receive it from You and pass it on. Thank You for loving me first. Help me to love others the same way. Amen."
  }
];


export default verses;